### ISSUE TITLE
resp_seq_id in RSP_nack PDUs

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPLib#10] opened 2019-05-28 07:29 UTC
I've set up a link between DcpTestGenerator and ExampleSlave implementation.
After receiving the RSP_nack PDU the DCP-Tester reports the wrong rsp_seq_id, throws a PduMissed exception, and stops the execution.

According to the DCP specification v1.0 p52 
The exp_seq_id equals pdu_seq_id_last incremented by 1 
resp_seq_id equals to the corresponding pdu_seq_id

Should the Implementation throw an pdu missed exception here?
Because the error code is different and the PDU was not missed.

Logs
```
DCP Slave
2019-05-27 17:23:18 	 DEBUG 		 UDP_IPv4 socket opened on 192.168.1.11:8080
2019-05-27 17:23:35 	 DEBUG 		 Pdu was received with content=type_id=STC_register pdu_seq_id=0 receiver=1 slave_uuid=b5279485-720d-4542-9f29-bee4d9a75ef9 state_id=CONFIGURATION op_mode=SRT major_version=1 minor_version=0
2019-05-27 17:23:35 	 ERROR 		 State id (CONFIGURATION) in received state change PDU do not match current state (ALIVE).
2019-05-27 17:23:35 	 DEBUG 		 Pdu was send with content=type_id=RSP_nack sender=1 resp_seq_id=0 exp_seq_id=1 error_code=INVALID_STATE_ID
```

```
DCP-Tester with Debugging on
Parsing found no errors
2019-05-27 17:23:33 	 DEBUG 		 UDP_IPv4 socket opened on 0.0.0.0:25000
create Automaton
Start Procedure
2019-05-27 17:23:35 	 DEBUG 		 Pdu was send with content=type_id=STC_register pdu_seq_id=0 receiver=1 slave_uuid=b5279485-720d-4542-9f29-bee4d9a75ef9 state_id=CONFIGURATION op_mode=SRT major_version=1 minor_version=0
2019-05-27 17:23:35 	 DEBUG 		 Pdu was received with content=type_id=RSP_nack sender=1 resp_seq_id=0 exp_seq_id=1 error_code=INVALID_STATE_ID
2019-05-27 17:23:45 	 INFO 		 A receiving rsp_seq_id for slave 1 was out of sync.
```

**Comment by martinkrammer** [comment] 2019-05-28 10:35
The state_id specified in the STC_register PDU is not correct. STC_register can only be processed in state ALIVE.

**Comment by clemensschiffer** [comment] 2019-05-28 10:50
I havent used the DCP-Tester so far but if 
> the DCP-Tester reports the wrong rsp_seq_id, throws a PduMissed exception, and stops the execution.
then the issue is with the Tester?  
In the log it reports the resp_seq_id=0 the correct response to the invalid PDU, right?

Maybe check if this is related to #7 where resp_seq_id and sender fields were swapped, but are now fixed, maybe the tester has the same issue?

**Comment by dev-gb** [comment] 2019-05-28 12:49
> then the issue is with the Tester?

The Tester implementation seems to be correct as far as i can tell.

> In the log it reports the resp_seq_id=0 the correct response to the invalid PDU, right?

Yes 
`INFO  A receiving rsp_seq_id for slave 1 was out of sync.` is printed out by the pduMissedListener


Found the error.
In the appropriate case, the callback is caused by the resp_seq_id = 0, since this is the initialization value of the segNumsIn array. So the send pdu_seq_id has to be initialized with a value unequal zero on startup. Would be better to check, if this was the first pdu.

https://github.com/modelica/DCPLib/blob/330344c577cf90558b637c492d3bbd4e9773cba1/include/master/dcp/logic/DcpManagerMaster.hpp#L74-L83

https://github.com/modelica/DCPLib/blob/330344c577cf90558b637c492d3bbd4e9773cba1/include/core/dcp/logic/AbstractDcpManager.hpp#L133-L140

Would be nice if someone could check the implementation with the DCPTester as I had some troubles with the pdu_seq_id. The example below should not throw a PduMissed.

```
DCPSlave
2019-05-28 14:06:02 	 DEBUG 		 Pdu was received with content=type_id=CFG_clear pdu_seq_id=30 receiver=1
2019-05-28 14:06:02 	 DEBUG 		 Pdu was send with content=type_id=RSP_ack sender=1 resp_seq_id=30
2019-05-28 14:06:02 	 DEBUG 		 Configuration cleared.
2019-05-28 14:06:02 	 DEBUG 		 Expected next pdu_seq_id from the master to be 24
2019-05-28 14:06:02 	 DEBUG 		 Pdu was received with content=type_id=CFG_input pdu_seq_id=24 receiver=1 data_id =0 pos=0 target_vr=2 source_data_type=float64
2019-05-28 14:06:02 	 DEBUG 		 Pdu was send with content=type_id=RSP_ack sender=1 resp_seq_id=24
```

```
DCP-Tester
2019-05-28 14:06:02 	 DEBUG 		 Pdu was send with content=type_id=CFG_clear pdu_seq_id=30 receiver=1
2019-05-28 14:06:02 	 DEBUG 		 Pdu was received with content=type_id=RSP_ack sender=1 resp_seq_id=30
2019-05-28 14:06:02 	 DEBUG 		 Pdu was send with content=type_id=CFG_input pdu_seq_id=24 receiver=1 data_id =0 pos=0 target_vr=2 source_data_type=float64
2019-05-28 14:06:02 	 DEBUG 		 Pdu was received with content=type_id=RSP_ack sender=1 resp_seq_id=24
2019-05-28 14:21:50 	 INFO 		 A receiving rsp_seq_id for slave 1 was out of sync.
```
` segNumsIn[acuId]` and `seqId` are both 24 after reset.

**Comment by clemensschiffer** [comment] 2019-05-29 10:02
Hey, so if I understand correctly:
segNumsIn is initialized with 0 so if a RSP_ack with resp_seq_id=0 is received then
checkSeqId returns 0(not 1) so a PduMissed is thrown.
(And similar after resetting the slave config)
Does this also happen in the example slave/master of the DCPLib? 
It also starts at pdu_seq_id=0 and does not crash ...

Are both slave and DCPTester(acting as master) build against the same version of the DCPLib? 
Since ack changed the Fields: sender<-> resp_seq_id ... 
@ChKater  do you know whats up with this?

**Comment by ChKater** [comment] 2019-05-29 10:13
I will check in the next days. 

@dev-gb can you provide me information about your environment (os, compiler).

**Comment by dev-gb** [comment] 2019-05-29 11:49
@clemensschiffer 

> segNumsIn` is initialized with 0 so if a RSP_ack with resp_seq_id=0 is received then checkSeqId returns 0(not 1) so a PduMissed is thrown.

Yes

> Does this also happen in the example slave/master of the DCPLib

The example slave does not register a PduMissedListener

implemented setPduMissedListener in the Master Example. Same behaviour here.

**Comment by ChKater** [comment] 2019-05-29 15:24
This problem should be solved now.

**Closed** 2019-06-03 07:22 UTC
